import { useEffect, useMemo, useState } from 'react'
import { Download, FlaskConical, Grid2X2, SlidersHorizontal } from 'lucide-react'
import { apiRequest } from '@/api/client'
import { Badge } from '@/components/analytics/Badge'
import { FilterToolbar } from '@/components/analytics/FilterToolbar'
import { KpiCard } from '@/components/analytics/KpiCard'
import { StatusPanel } from '@/components/analytics/StatusPanel'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import type { DatasetSummary } from '@/features/encuesta/api'
import type { AnalyticsSummary, CategoryDistribution } from './api'

type Domain = 'TITULADOS' | 'EMPLEADORES'
type Tone = 'titulados' | 'empleadores'
type Competence = { code: string; name: string; group: string; validCount: number; average: number; standardDeviation: number | null }
type Cross = { validCount: number; rowCategories: string[]; columnCategories: string[]; counts: Record<string, Record<string, number>>; percentages: Record<string, Record<string, number>>; smallSample: boolean }
type Simulation = { sampleSize: number; repetitions: number; seed: number; categories: { category: string; observedPercentage: number; simulatedMean: number; lower95: number; upper95: number }[] }

export function DatasetAnalyticsPage({ title, description, domain, endpoint, fields, cards }: { title: string; description: string; domain: Domain; endpoint: string; fields?: string; cards: { key: string; label: string }[] }) {
  const tone: Tone = domain === 'TITULADOS' ? 'titulados' : 'empleadores'
  const { datasets, datasetId, setDatasetId, loading: datasetsLoading } = useDatasets(domain)
  const [summary, setSummary] = useState<AnalyticsSummary | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  useEffect(() => { if (!datasetId) { setSummary(null); setLoading(false); return }; setLoading(true); setError(null); const suffix = fields ? `&fields=${encodeURIComponent(fields)}` : ''; apiRequest<AnalyticsSummary>(`${endpoint}?datasetId=${encodeURIComponent(datasetId)}${suffix}`).then(setSummary).catch((cause) => setError(cause instanceof Error ? cause.message : String(cause))).finally(() => setLoading(false)) }, [datasetId, endpoint, fields])
  return <div className="mx-auto max-w-6xl space-y-6"><PageHeading title={title} description={description} tone={tone} /><DatasetSelect datasets={datasets} value={datasetId} onChange={setDatasetId} loading={datasetsLoading} />{loading && <StatusPanel kind="loading" title="Cargando datos" description="Consultando el dataset seleccionado." />}{error && <StatusPanel kind="warning" title="No se pudo cargar la pantalla" description={error} />}{!loading && !error && !summary && <StatusPanel kind="info" title={`Sin dataset de ${domain.toLowerCase()}`} description="Importa un dataset compatible para habilitar esta vista." />}{summary && <><FilterToolbar count={`${summary.validResponses} respuestas válidas`} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map((card) => <KpiCard key={card.key} label={card.label} value={formatMetric(summary, card.key)} detail={summary.distributions[card.key] ? `${summary.distributions[card.key].validCount} respuestas` : 'Dato numérico'} note={`n = ${summary.distributions[card.key]?.validCount ?? summary.validResponses}`} tone={tone} />)}</div><div className="grid gap-6 lg:grid-cols-2">{Object.entries(summary.distributions).map(([key, distribution]) => <DistributionCard key={key} title={labelFor(key)} distribution={distribution} tone={tone} />)}</div></>}</div>
}

export function CompetencePage({ domain }: { domain: Domain }) {
  const tone: Tone = domain === 'TITULADOS' ? 'titulados' : 'empleadores'; const { datasets, datasetId, setDatasetId, loading: datasetsLoading } = useDatasets(domain); const [items, setItems] = useState<Competence[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (!datasetId) { setItems([]); return }; setLoading(true); setError(null); apiRequest<Competence[]>(`/analytics/competencies/gaps?datasetId=${encodeURIComponent(datasetId)}`).then(setItems).catch((cause) => setError(cause instanceof Error ? cause.message : String(cause))).finally(() => setLoading(false)) }, [datasetId])
  const groups = useMemo(() => [...new Set(items.map((item) => item.group))], [items])
  return <div className="mx-auto max-w-6xl space-y-6"><PageHeading title="Brechas de competencias" description="Medias y desviaciones estándar por competencia. No observado se excluye del cálculo." tone={tone} /><DatasetSelect datasets={datasets} value={datasetId} onChange={setDatasetId} loading={datasetsLoading} />{loading && <StatusPanel kind="loading" title="Cargando competencias" description="Consultando las valoraciones del dataset." />}{error && <StatusPanel kind="warning" title="No se pudo cargar competencias" description={error} />}{!loading && !error && !datasetId && <StatusPanel kind="info" title="Sin dataset seleccionado" description="Selecciona o importa un dataset para mostrar la tabla." />}{items.length > 0 && groups.map((group) => <Card key={group}><CardHeader><CardTitle className="title-card">{group}</CardTitle><CardDescription>Media y desviación estándar · escala de 1 a 5</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-ink-600"><th className="p-2">Competencia</th><th className="p-2 text-right">n</th><th className="p-2 text-right">Media</th><th className="p-2 text-right">Desv. estándar</th></tr></thead><tbody>{items.filter((item) => item.group === group).map((item) => <tr key={item.code} className="border-b border-slate-100"><td className="p-2">{item.name}</td><td className="tabular-nums p-2 text-right">{item.validCount}</td><td className="tabular-nums p-2 text-right">{item.average.toFixed(2)}</td><td className="tabular-nums p-2 text-right">{item.standardDeviation === null ? '—' : item.standardDeviation.toFixed(2)}</td></tr>)}</tbody></table></div></CardContent></Card>)}</div>
}

export function CrossExportPage({ domain }: { domain: Domain }) {
  const tone: Tone = domain === 'TITULADOS' ? 'titulados' : 'empleadores'; const { datasets, datasetId, setDatasetId, loading: datasetsLoading } = useDatasets(domain); const [rowField, setRowField] = useState(domain === 'TITULADOS' ? 'situacion_laboral_actual' : 'tipo_organizacion'); const [columnField, setColumnField] = useState(domain === 'TITULADOS' ? 'interes_posgrado' : 'tamano_organizacion'); const [cross, setCross] = useState<Cross | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false)
  async function loadCross() { if (!datasetId) return; setLoading(true); setError(null); try { setCross(await apiRequest<Cross>(`/analytics/crosses?datasetId=${encodeURIComponent(datasetId)}&rowField=${encodeURIComponent(rowField)}&columnField=${encodeURIComponent(columnField)}`)) } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } finally { setLoading(false) } }
  return <div className="mx-auto max-w-6xl space-y-6"><PageHeading title="Cruces y exportación" description="Configura una matriz de frecuencias y revisa sus porcentajes por fila." tone={tone} /><DatasetSelect datasets={datasets} value={datasetId} onChange={setDatasetId} loading={datasetsLoading} /><Card><CardHeader><CardTitle className="title-card flex items-center gap-2"><Grid2X2 className="size-5" />Configuración del cruce</CardTitle><CardDescription>Las exportaciones respetan la matriz calculada y no incluyen datos personales.</CardDescription></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2"><label className="label-default grid gap-1">Variable de filas<input className="control" value={rowField} onChange={(event) => setRowField(event.target.value)} /></label><label className="label-default grid gap-1">Variable de columnas<input className="control" value={columnField} onChange={(event) => setColumnField(event.target.value)} /></label></div><div className="mt-4 flex flex-wrap gap-2"><Button onClick={loadCross} disabled={!datasetId || loading}><SlidersHorizontal />{loading ? 'Calculando…' : 'Calcular cruce'}</Button><Button variant="outline" onClick={() => cross && exportCrossCsv(cross)} disabled={!cross}><Download />CSV</Button><Button variant="outline" onClick={() => cross && exportCrossExcel(cross)} disabled={!cross}><Download />Excel (.xls)</Button><Button variant="outline" onClick={() => cross && exportCrossPng(cross)} disabled={!cross}><Download />PNG</Button></div></CardContent></Card>{error && <StatusPanel kind="warning" title="No se pudo calcular el cruce" description={error} />}{cross && <CrossTable cross={cross} />}</div>
}

export function SimulationPage() {
  const { datasets, datasetId, setDatasetId, loading: datasetsLoading } = useDatasets('TITULADOS')
  const [summary, setSummary] = useState<AnalyticsSummary | null>(null); const [sampleSize, setSampleSize] = useState(100); const [repetitions, setRepetitions] = useState(1000); const [seed, setSeed] = useState(42); const [result, setResult] = useState<Simulation | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (!datasetId) return; apiRequest<AnalyticsSummary>(`/analytics/titulados/summary?datasetId=${encodeURIComponent(datasetId)}&fields=interes_posgrado`).then(setSummary).catch((cause) => setError(cause instanceof Error ? cause.message : String(cause))) }, [datasetId])
  async function run() { const distribution = summary?.distributions.interes_posgrado; if (!distribution) return; const categories = Object.keys(distribution.counts); const total = categories.reduce((sum, category) => sum + distribution.counts[category], 0); setLoading(true); setError(null); try { setResult(await apiRequest<Simulation>('/analytics/simulation/multinomial', { method: 'POST', body: JSON.stringify({ categories, probabilities: categories.map((category) => distribution.counts[category] / total), sampleSize, repetitions, seed }) })) } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } finally { setLoading(false) } }
  return <div className="mx-auto max-w-6xl space-y-6"><PageHeading title="Simulación de escenarios" description="Simulación multinomial descriptiva usando las frecuencias observadas como probabilidades." tone="titulados" /><DatasetSelect datasets={datasets} value={datasetId} onChange={setDatasetId} loading={datasetsLoading} /><Card><CardHeader><CardTitle className="title-card">Parámetros</CardTitle><CardDescription>La semilla permite repetir el mismo escenario. No es una predicción.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-3"><label className="label-default grid gap-1">Personas a simular<input className="control" type="number" min="1" value={sampleSize} onChange={(event) => setSampleSize(Number(event.target.value))} /></label><label className="label-default grid gap-1">Repeticiones<input className="control" type="number" min="1" value={repetitions} onChange={(event) => setRepetitions(Number(event.target.value))} /></label><label className="label-default grid gap-1">Semilla<input className="control" type="number" value={seed} onChange={(event) => setSeed(Number(event.target.value))} /></label><div className="sm:col-span-3"><Button onClick={run} disabled={!summary || loading}>{loading ? 'Ejecutando…' : 'Ejecutar simulación'}</Button></div></CardContent></Card>{error && <StatusPanel kind="warning" title="No se pudo ejecutar la simulación" description={error} />}{result && <Card><CardHeader><CardTitle className="title-card">Resultado simulado</CardTitle><CardDescription>Promedio y rango del 95 % · n observado = {summary?.distributions.interes_posgrado?.validCount ?? 0}</CardDescription></CardHeader><CardContent><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-ink-600"><th className="p-2">Categoría</th><th className="p-2 text-right">Observado</th><th className="p-2 text-right">Simulado</th><th className="p-2 text-right">Rango 95 %</th></tr></thead><tbody>{result.categories.map((category) => <tr key={category.category} className="border-b border-slate-100"><td className="p-2">{category.category}</td><td className="tabular-nums p-2 text-right">{category.observedPercentage}%</td><td className="tabular-nums p-2 text-right">{category.simulatedMean}%</td><td className="tabular-nums p-2 text-right">{category.lower95}% – {category.upper95}%</td></tr>)}</tbody></table></CardContent></Card>}</div>
}

export function UnavailableAnalyticPage({ title, description, domain, items }: { title: string; description: string; domain: Domain; items: string[] }) { const tone: Tone = domain === 'TITULADOS' ? 'titulados' : 'empleadores'; return <div className="mx-auto max-w-6xl space-y-6"><PageHeading title={title} description={description} tone={tone} /><Card><CardHeader><CardTitle className="title-card flex items-center gap-2"><FlaskConical className="size-5" />Funcionalidad pendiente de contrato</CardTitle><CardDescription>La ruta está preparada, pero el backend todavía no expone los datos necesarios para mostrar resultados.</CardDescription></CardHeader><CardContent className="space-y-3"><StatusPanel kind="info" title="No disponible todavía" description="No se muestran valores manuales ni simulados como si fueran resultados reales." />{items.map((item) => <div key={item} className="rounded-lg border border-border-line bg-slate-50 p-3 text-sm text-ink-600">{item}</div>)}</CardContent></Card></div> }

function useDatasets(domain: Domain) { const [datasets, setDatasets] = useState<DatasetSummary[]>([]); const [datasetId, setDatasetIdState] = useState<string | undefined>(); const [loading, setLoading] = useState(true); useEffect(() => { apiRequest<DatasetSummary[]>('/datasets').then((items) => { const filtered = items.filter((item) => item.surveyType === domain); setDatasets(filtered); const stored = localStorage.getItem('simulacionem.activeDatasetId'); setDatasetIdState(filtered.some((item) => item.id === stored) ? stored ?? undefined : filtered.at(-1)?.id) }).finally(() => setLoading(false)) }, [domain]); const setDatasetId = (id?: string) => { setDatasetIdState(id); if (id) localStorage.setItem('simulacionem.activeDatasetId', id) }; return { datasets, datasetId, setDatasetId, loading } }
function PageHeading({ title, description, tone }: { title: string; description: string; tone: Tone }) { return <div className="space-y-2"><div className="flex items-center gap-3"><p className="caption-bold uppercase tracking-wider text-ink-600">SimulacionEM</p><Badge tone={tone}>{tone === 'titulados' ? 'Titulados' : 'Empleadores'}</Badge></div><h1 className="headline-page">{title}</h1><p className="max-w-2xl text-sm text-ink-600">{description}</p></div> }
function DatasetSelect({ datasets, value, onChange, loading }: { datasets: DatasetSummary[]; value?: string; onChange: (id?: string) => void; loading: boolean }) { return <div className="flex flex-wrap items-center gap-3"><label className="label-default text-ink-600">Dataset<select className="control ml-2" value={value ?? ''} disabled={loading} onChange={(event) => onChange(event.target.value || undefined)}><option value="">Seleccionar dataset</option>{datasets.map((dataset) => <option key={dataset.id} value={dataset.id}>{dataset.sourceFileName} · {dataset.rowsValid} válidas</option>)}</select></label></div> }
function DistributionCard({ title, distribution, tone }: { title: string; distribution: CategoryDistribution; tone: Tone }) { return <Card><CardHeader><CardTitle className="title-card">{labelFor(title)}</CardTitle><CardDescription>Conteo y porcentaje · n = {distribution.validCount}</CardDescription></CardHeader><CardContent className="space-y-3">{Object.entries(distribution.counts).map(([key, count]) => <div key={key} className="space-y-1"><div className="flex justify-between text-sm"><span>{key}</span><span className="tabular-nums">{count} · {distribution.percentages[key]}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className={`h-full rounded-full ${tone === 'titulados' ? 'bg-titulados' : 'bg-empleadores'}`} style={{ width: `${distribution.percentages[key]}%` }} /></div></div>)}</CardContent></Card> }
function CrossTable({ cross }: { cross: Cross }) { return <Card><CardHeader><CardTitle className="title-card">Vista previa de matriz</CardTitle><CardDescription>n = {cross.validCount}{cross.smallSample ? ' · muestra reducida' : ''}</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Fila</th>{cross.columnCategories.map((column) => <th key={column} className="p-2 text-right">{column}</th>)}</tr></thead><tbody>{cross.rowCategories.map((row) => <tr key={row} className="border-t"><td className="p-2">{row}</td>{cross.columnCategories.map((column) => <td key={column} className="tabular-nums p-2 text-right">{cross.counts[row]?.[column] ?? 0}</td>)}</tr>)}</tbody></table></CardContent></Card> }
function formatMetric(summary: AnalyticsSummary, key: string) { const distribution = summary.distributions[key]; if (distribution) return `${distribution.validCount}`; return summary.numericAverages[key] === undefined ? '—' : String(summary.numericAverages[key]) }
function labelFor(key: string) { return key.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()) }
function downloadFile(content: BlobPart, name: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url) }
function exportCrossCsv(cross: Cross) { const rows = [['Fila', ...cross.columnCategories], ...cross.rowCategories.map((row) => [row, ...cross.columnCategories.map((column) => String(cross.counts[row]?.[column] ?? 0))])]; downloadFile(rows.map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(',')).join('\n'), 'cruce.csv', 'text/csv;charset=utf-8') }
function exportCrossExcel(cross: Cross) { const rows = [['Fila', ...cross.columnCategories], ...cross.rowCategories.map((row) => [row, ...cross.columnCategories.map((column) => String(cross.counts[row]?.[column] ?? 0))])]; const html = `<table>${rows.map((row) => `<tr>${row.map((cell) => `<td>${cell}</td>`).join('')}</tr>`).join('')}</table>`; downloadFile(`<!doctype html><html><body>${html}</body></html>`, 'cruce.xls', 'application/vnd.ms-excel') }
function exportCrossPng(cross: Cross) { const width = 900; const height = Math.max(180, (cross.rowCategories.length + 1) * 42 + 40); const headers = ['Fila', ...cross.columnCategories]; const rows = [headers, ...cross.rowCategories.map((row) => [row, ...cross.columnCategories.map((column) => String(cross.counts[row]?.[column] ?? 0))])]; const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="100%" height="100%" fill="white"/>${rows.map((row, rowIndex) => row.map((cell, columnIndex) => `<text x="${20 + columnIndex * (width / headers.length)}" y="${35 + rowIndex * 42}" font-family="Arial" font-size="14" fill="#0f172a">${cell}</text>`).join('')).join('')}</svg>`; const image = new Image(); image.onload = () => { const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; canvas.getContext('2d')?.drawImage(image, 0, 0); canvas.toBlob((blob) => blob && downloadFile(blob, 'cruce.png', 'image/png')) }; image.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}` }

