spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5433}/simulacionem
    username: simulacionem_dev
    password: dev_password_2026
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
